#!/usr/bin/env bash
#groups visitors by IP and HTTP status code, and displays this data.
awk '{count[$1" "$9]++} END {for (combo in count) print count[combo], combo}' apache-access.log |
sort -rn |
awk '{print $2, $3, $1}'
