#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
var=1
while [ $var -le 10 ]
do
	if [$var -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((var))
done

