#!/usr/bin/env bash
#script that displays the content of the current directory
for file in *; do
    if [[ ! $file == .* && $file =~ - ]]; then
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
