#!/usr/bin/env bash
#configures an Ubuntu server with the
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run with sudo" 1>&2
    exit 1
fi

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

systemd-resolve --flush-caches

echo "IP addresses configured successfully!"
