#!/usr/bin/env bash
# Configuring Nginx to serve /airbnb-onepage and proxy to port 5000

sudo apt update
sudo apt install -y nginx

cat <<EOF | sudo tee /etc/nginx/sites-available/default > /dev/null
server {
   listen 80 default_server;
   listen [::]:80 default_server;
   server_name _;
   
   location / {
      try_files \$uri \$uri/ =404;
   }

   location /airbnb-onepage/ {
      proxy_pass http://127.0.0.1:5000;
      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
   }
   error_page 500 502 503 504 /50x.html;
   location = /50x.html {
      root /usr/share/nginx/html; 
   }
}
EOF
sudo nginx -t && sudo systemctl restart nginx
