#!/usr/bin/env bash
#configuting nginx to listen to  2 diff ports
server {
   listen 80 default_server;
   listen [::]:80 default_server;
   server_name _;

   location / {
      try_files $uri $uri/ =404;
   }

   location /airbnb-onepage/ {
      proxy_pass http://127.0.0.1:5000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
   }
   location ~ ^/airbnb-dynamic/number_odd_or_even/(\d+)$ {
      set $number $1;
      proxy_pass http://127.0.0.1:5001/number_odd_or_even/$number;
      proxy_set_header Host \$host;
      proxy_set_header X-Real-IP \$remote_addr;
      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto \$scheme;
   }
   error_page 500 502 503 504 /50x.html;
   location = /50x.html {
      root /usr/share/nginx/html;
   }
}
